ARG imagename

FROM --platform=$TARGETPLATFORM ${imagename}

RUN set -x \
    && yum install -y ruby-devel rubygems gcc make rpmdevtools git \
    && gem install fpm \
    && yum clean all \
    && mkdir /src

WORKDIR /src/

CMD /usr/local/bin/fpm
