# Builds SonoBus from source using a pre-built base image
ARG BUILD_IMAGE

FROM --platform=$TARGETPLATFORM ${BUILD_IMAGE}

ARG BRANCH=main

RUN mkdir -p /dist/usr
RUN git clone -b "${BRANCH}" --single-branch --depth 1 https://github.com/sonosaurus/sonobus.git

WORKDIR sonobus/linux
RUN set -x && ./build.sh && ./install.sh /dist/usr && strip --strip-unneeded /dist/usr/bin/sonobus
