# FPM packaging tool for RPM-based systems
ARG BASE_IMAGE=fedora:latest

FROM --platform=$TARGETPLATFORM ${BASE_IMAGE}

RUN set -x \
    && dnf install -y ruby-devel gcc make rpmdevtools \
    && gem install fpm \
    && dnf clean all \
    && mkdir /src

WORKDIR /src

CMD ["/usr/local/bin/fpm"]
