# FPM packaging tool for Debian-based systems
ARG BASE_IMAGE=ubuntu:jammy

FROM --platform=$TARGETPLATFORM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential git ruby ruby-dev gcc make \
        ca-certificates libffi-dev ruby-ffi \
    && gem install fpm \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /src

WORKDIR /src

CMD ["/usr/local/bin/fpm"]
